In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [13]:
print(x)

[['Semarang' 45.0 75000.0]
 ['Jakarta' 25.0 47000.0]
 ['Surabaya' 30.0 52000.0]
 ['Semarang' 35.0 58000.0]
 ['Jakarta' 40.0 nan]
 ['Bandung' 35.0 55000.0]
 ['Semarang' nan 51000.0]
 ['Surabaya' 45.0 76000.0]
 ['Jakartaa' 50.0 83000.0]
 ['Bandung' 35.0 65000.0]]


In [14]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [17]:
print(x)

[['Semarang' 45.0 75000.0]
 ['Jakarta' 25.0 47000.0]
 ['Surabaya' 30.0 52000.0]
 ['Semarang' 35.0 58000.0]
 ['Jakarta' 40.0 62444.444444444445]
 ['Bandung' 35.0 55000.0]
 ['Semarang' 37.77777777777778 51000.0]
 ['Surabaya' 45.0 76000.0]
 ['Jakartaa' 50.0 83000.0]
 ['Bandung' 35.0 65000.0]]


In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [19]:
print(x)

[[0.0 0.0 0.0 1.0 0.0 45.0 75000.0]
 [0.0 1.0 0.0 0.0 0.0 25.0 47000.0]
 [0.0 0.0 0.0 0.0 1.0 30.0 52000.0]
 [0.0 0.0 0.0 1.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 0.0 40.0 62444.444444444445]
 [1.0 0.0 0.0 0.0 0.0 35.0 55000.0]
 [0.0 0.0 0.0 1.0 0.0 37.77777777777778 51000.0]
 [0.0 0.0 0.0 0.0 1.0 45.0 76000.0]
 [0.0 0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 35.0 65000.0]]


In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [21]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state= 1)

In [23]:
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 37.77777777777778 51000.0]
 [0.0 1.0 0.0 0.0 0.0 40.0 62444.444444444445]
 [0.0 0.0 0.0 1.0 0.0 45.0 75000.0]
 [0.0 0.0 0.0 1.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 0.0 25.0 47000.0]
 [0.0 0.0 0.0 0.0 1.0 45.0 76000.0]
 [0.0 0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 35.0 55000.0]]


In [24]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 30.0 52000.0]
 [1.0 0.0 0.0 0.0 0.0 35.0 65000.0]]


In [25]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [26]:
print(y_test)

[0 1]


In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [30]:
print(x_train)

[[0.0 0.0 0.0 1.2909944487358056 -0.3779644730092272 -0.1813641047632719
  -1.0146016407569238]
 [0.0 1.0 0.0 -0.7745966692414834 -0.3779644730092272 0.1240912295748705
  -0.08048795138965528]
 [0.0 0.0 0.0 1.2909944487358056 -0.3779644730092272 0.811365731835691
  0.944316387430746]
 [0.0 0.0 0.0 1.2909944487358056 -0.3779644730092272 -0.5631832726859501
  -0.44325054920218676]
 [0.0 1.0 0.0 -0.7745966692414834 -0.3779644730092272 -1.9377322772075913
  -1.3410879787882022]
 [0.0 0.0 0.0 -0.7745966692414834 2.6457513110645903 0.811365731835691
  1.0259379719385655]
 [0.0 0.0 1.0 -0.7745966692414834 -0.3779644730092272 1.4986402340965117
  1.5972890634933026]
 [1.0 0.0 0.0 -0.7745966692414834 -0.3779644730092272 -0.5631832726859501
  -0.6881153027256455]]


In [31]:
print(x_test)

[[0.0 0.0 0.0 -0.7745966692414834 2.6457513110645903 -1.2504577749467707
  -0.9329800562491042]
 [1.0 0.0 0.0 -0.7745966692414834 -0.3779644730092272 -0.5631832726859501
  0.12810054235255022]]
